services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  test_db:
    image: postgres:18
    environment:
      POSTGRES_DB: blog_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  api:
    image: ghcr.io/anas-kaithakoden/blog-api:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      TEST_DATABASE_URL: postgresql+psycopg://postgres:123@test_db:5432/blog_test_db
      SECRET_KEY : ${SECRET_KEY}

    ports:
      - "8000:8000" 
    depends_on:
      - db
      - test_db


volumes:
  postgres_data:
  